1630631126	ERROR: HTTPConnectionPool(host='data.gdeltproject.org', port=80): Max retries exceeded with url: /gdeltv2/lastupdate.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114dfc970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
1630632718	ERROR: HTTPConnectionPool(host='data.gdeltproject.org', port=80): Max retries exceeded with url: /gdeltv2/lastupdate.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11bad1a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
